<?php
if (!defined("MODULE_FILE")) {Header("Location: ../../index.php");exit;}
get_lang($conf['name']);
include_once ('config/config_global.php');
include_once ('config/config_offline.php');

if ($offline['status']=='0' || ($offline['type']=='0' && ($offline['autorun']=='1' && strtotime($offline['open'])<=time() || strtotime($offline['close'])>time()))) {Header("Location: /");die();}

$content='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><title>'.OFFLINE_1.'</title><meta http-equiv="content-type" content="text/html; charset=utf-8"><link rel="stylesheet" href="modules/offline/function/style.css?'.filemtime("modules/offline/function/style.css").'" type="text/css" media="all"/><script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script><script type="text/javascript" src="modules/offline/function/function.js?'.filemtime("modules/offline/function/function.js").'"></script><script type="text/javascript">$(document).ready(function() { changeContainerPosition(); $(window).bind("resize", function(){changeContainerPosition();}); var launchDate = new Date("'.$offline['open'].'"); var closeDate = new Date("'.$offline['close'].'"); var secondsRemaining = Math.floor(launchDate.getTime()/1000) - Math.floor(new Date().getTime()/1000); var sto = Math.floor(launchDate.getTime()/1000)-Math.floor(closeDate.getTime()/1000); countdown(secondsRemaining); updateProgress({"close":Math.floor(closeDate.getTime()/1000),"open":Math.floor(launchDate.getTime()/1000)}); });</script> </head> <body> <table width="100%" border="0" cellspacing="0" cellpadding="0"> <div class="container"> <div class="header hd"></div><div class="content"><h1>'.$conf['slogan'].'</h1><div class="space20"></div><h3>'.OFFLINE_2.'</h3><div class="space11"></div><div class="countdownTimerWrap clear"><div class="countdownTimer"><div class="days"><div class="number">00</div><div class="text">'.OFFLINE_3.'</div></div><div class="splitter">:</div><div class="hours"><div class="number">00</div><div class="text">'.OFFLINE_4.'</div></div><div class="splitter">:</div><div class="minutes"><div class="number">00</div><div class="text">'.OFFLINE_5.'</div></div><div class="splitter">:</div><div class="seconds"><div class="number">00</div><div class="text">'.OFFLINE_6.'</div></div></div></div><div style="clear:both;"></div><div class="space28"></div><div class="progressBar"> <div class="progressBarFill blue clear"><div class="progressBarFillLeft"></div><div class="progressBarFillRight"></div><div class="progressBarFillMiddle">100%</div></div></div><div class="space14"></div><div class="progressDescription"><div class="progressDescriptionHeader"></div><div class="progressDescriptionMiddle">'.OFFLINE_7.$offline['reason'].'</div><div class="progressDescriptionFooter"></div></div><div class="space24"></div></div><div class="footer"></div></div></body></html>';
echo $content;

?>