<?php
if (!defined("FUNC_FILE")) die("Illegal File Access");

include ('config/config_thanks_op.php');
function thanks_encode ($a) { global $thanks; if ($thanks['charset']=='windows-1251') { header('Content-type: text/html; charset=windows-1251'); foreach ($a as $b=>$c) $d[]='"'.$b.'":"'.addcslashes(str_replace(array("\r","\n"),"",$c), '"').'"'; return '{'.implode(',',$d).'}'; } else return json_encode($a); }
function thanks_sclon ($a, $text){$slova = explode('|',$text);if (count($slova)!='3') return $text;else {$i=intval($a);if($i%10==1 && $i%100!=11)$out_str=$slova[0];elseif($i%10>=2&&$i%10<=4&&($i%100<10||$i%100>=20)) $out_str=$slova[1];else $out_str=$slova[2];return $out_str;}}
function check_thanks($a,$b='') { global $db,$prefix,$user,$thnks; if (is_array($thnks) && $b=='') return $thnks; else { unset($thnks); $sql=$db->sql_query("SELECT `mid`,`name` FROM `".$prefix."_thanks` WHERE `module`='$a'".(($b!='')?" AND `mid`='$b'":'')); while(list($mid,$name)=$db->sql_fetchrow($sql)) $thnks[$mid][]=$name; return $thnks; }}
function save_thanks($a,$b) { global $thanks,$user,$db,$prefix; if ($a!='' && $b>0 && is_user() && $thanks['module'][$a]['status']==1) { $c=check_thanks($a,$b); if (is_array($c[$b]) && in_array($user[1],$c[$b])) { $out['text']=_THANKS_1; $out['html']=show_thanks($a,$b,$user[0]); $out['status']=0; } else { if (intval($thanks['module'][$a]['uid'])!=-1) { $sql=$db->sql_query(strtr($thanks['module'][$a]['uid'],array('{id}'=>$b))); list($uid)=$db->sql_fetchrow($sql); } else $uid=-1; if ($uid==$user[0]) { $out['text']=_THANKS_2; $out['html']=show_thanks($a,$b,$user[0]); $out['status']=0; } else { if ($uid>0) { $db->sql_query("INSERT INTO ".$prefix."_thanks_user (id,uid,count,thanks) VALUES (NULL,'$uid','0','1') ON DUPLICATE KEY UPDATE thanks=thanks+1"); $db->sql_query("INSERT INTO ".$prefix."_thanks_user (id,uid,count,thanks) VALUES (NULL,'".$user[0]."','1','0') ON DUPLICATE KEY UPDATE count=count+1"); } $db->sql_query("INSERT INTO ".$prefix."_thanks (id,mid,module,name,date) VALUES (NULL,'$b','$a','".$user[1]."',now())"); $out['text']=_THANKS_3; $out['html']=show_thanks($a,$b,$user[0]); $out['status']=1; } } echo thanks_encode($out); } elseif ($thanks['module'][$a]['status']!=1) { $out['text']=_THANKS_4; $out['html']=show_thanks($a,$b,$user[0]); $out['status']=0; echo thanks_encode($out); } }
function show_thanks($a,$b,$c,$d=0) { global $user,$thanks; $text=''; $out=check_thanks($a,(($d==0)?$b:'')); $button = (is_user() && $thanks['module'][$a]['status']==1 && $c!=$user[0])?'<a href="#" class="thanks_button thanks_green thanks_medium" onclick="add_thanks(\''.$b.'\',\''.$a.'\'); return false;">'._THANKS_5.'</a>':''; if (is_array($out[$b])) { if (in_array($user[1],$out[$b])) $button='<span class="thanks_button thanks_white thanks_medium">'._THANKS_6.'</span>'; $text.='<span class="html">'; $text.='<span class="th-clr">'._THANKS_7.'</span>:<span class="th-url"><a href="#" title="'._THANKS_8.'" class="thanks-sh" id="thsh-'.$a.'-'.$b.'">'.count($out[$b]).' '.thanks_sclon(count($out[$b]),_THANKS_9).'</a></span>'; array_walk($out[$b], create_function('&$val', '$val = "<a href=\'index.php?name=account&op=info&uname=$val\' title=\'"._THANKS_11."\'>$val</a>";')); $text.='<div class="thanks-hide thsh-'.$a.'-'.$b.'"><span class=\'th-url\'>('.implode(', ',$out[$b]).')</span></div>'; $text.='</span>'; } else $text.='<span class="htaccess"><span class="th-clr">'._THANKS_10.'</span></span>'; return '<div id="thanks-'.$a.'-'.$b.'"><div>'.$button.'</div><div><span id="thanks-headers">'.$text.'</span></span></div></div>'; }
?>