<?php
if (!defined("FUNC_FILE")) die("Illegal File Access");

include ('config/config_invate.php');
include ('config/config_invate_op.php');
function getGuid(){mt_srand((double)microtime()*10000); $charid = strtoupper(md5(uniqid(rand(), true))); $hyphen = chr(45); $uuid = substr($charid,0,8).$hyphen.substr($charid,8,4).$hyphen.substr($charid,12,4).$hyphen.substr($charid,16,4).$hyphen.substr($charid,20,8);return $uuid;}
function invate_save($in=array()) { global $db,$prefix,$user,$invate,$conf; if (!isset($in['uid']) && is_user()) $in['uid']=$user[0]; if (isset($in['expire'])) $in['expire']=($in['expire']!=0)?date('Y-m-d H:i:s',time()+$in['expire']*60*60*24):0; elseif ($invate['live']>0) $in['expire']=date('Y-m-d H:i:s',time()+$invate['live']*60*60*24); else $in['expire']=0; $in['invate']=getGuid(); $db->sql_query("INSERT INTO ".$prefix."_invates (id,invate,email,uid,nuid,date,end_date,coast) VALUES (NULL,'".$in['invate']."','".$in['mail']."','".$in['uid']."','0',now(),'".$in['expire']."','".$invate['coast']."')"); if ($in['uid']<=0) $in['uid']='<strong>'._INVATE_60.'</strong>'; else $in['uid']=_INVATE_50.'<a href="'.rtrim($conf['homeurl'],'/').'/index.php?name=account&op=info&uname='.$user[1].'" title="'._INVATE_40.'">'.$user[1].'</a>'; if ($in['expire']==0) $in['expire']='<strong>'._INVATE_37.'</strong>'; else $in['expire']=invate_date($in['expire'],true); $in['invite_url']='<a href="'.rtrim($conf['homeurl'],'/').'/index.php?name=account&op=newuser&invate='.$in['invate'].'&mail='.$in['mail'].'" title="'._INVATE_41.'">'.rtrim($conf['homeurl'],'/').'/index.php?name=account&op=newuser&invate='.$in['invate'].'&mail='.$in['mail'].'</a>'; return array('{invate}'=>$in['invate'],'{site_url}'=>rtrim($conf['homeurl'],'/'),'{site_name}'=>$conf['sitename'],'{expire}'=>$in['expire'],'{user}'=>$in['uid'],'{invite_url}'=>$in['invite_url']); }
function invate_list () { global $uinf,$user,$ipoints,$db,$prefix,$invate; if (is_array($uinf[$user[0]])) return $uinf; else { $m=0; foreach ($ipoints['types'] as $a=>$b) { $sql=''; if ($b[0]==1) { $uinf['list'][$a]['lang']=explode('|',$b[1]); $sql=$db->sql_query("SELECT ".$b['sql']['select']." FROM `".$prefix."_".$b['sql']['table']."` WHERE ".$b['sql']['where']."=".$user[0]); list($uinf['list'][$a]['detail']['count']) = $db->sql_fetchrow($sql); if ($uinf['list'][$a]['detail']['count']<0) $uinf['list'][$a]['detail']['count']=0; $uinf['list'][$a]['detail']['summ']=ceil($uinf['list'][$a]['detail']['count']*$invate['points'][$a]); $uinf['list'][$a]['detail']['one']=$invate['points'][$a]; $m=$m+$uinf['list'][$a]['detail']['summ']; } } $uinf['summ']=$m; return $uinf; } }
function invate_expire($m=0) { global $db,$prefix; $out=$o=array(); if (is_admin() && $m==1 && isset($_POST['id']) && count($_POST['id'])>0) $where=' id IN ('.implode(',',$_POST['id']).')'; else $where="`end_date`!=0 AND `end_date`<now() AND `nuid`='0'"; $sql=$db->sql_query("SELECT id,uid,coast FROM ".$prefix."_invates WHERE ".$where); while(list($id,$uid,$coast)=$db->sql_fetchrow($sql)) {$out[$uid]=$out[$uid]+$coast;$o[]=$id;} if (count($o)>0) { foreach ($out as $a=>$b) {if ($a>0) $db->sql_query("UPDATE ".$prefix."_invates_points SET expend=expend-$b WHERE `uid`='$a'"); echo "UPDATE ".$prefix."_invates_points SET expend=expend-$b WHERE `uid`='$a'";} $db->sql_query("DELETE FROM ".$prefix."_invates WHERE `id` IN (".implode(',',$o).")"); } }
function invate_date($date, $is_time=false, $type='rus') {if (is_integer($date)) {$date=intval($date);$date=date('Y-m-d H:i:s', $date);}list($day, $time) = explode(' ', $date);if ($type=='-') return $day;elseif ($type!='rus') return implode($type, explode('-',$day));switch($day) {case date('Y-m-d'):$result = _INVATE_35;break;case date( 'Y-m-d', mktime(0, 0, 0, date("m"), date("d")-1, date("Y")) ):$result = _INVATE_36;break;default: {list($y, $m, $d)  = explode('-', $day);$result = $d.' '.str_replace(array('01','02','03','04','05','06','07','08','09','10','11','12'), explode(',',_INVATE_34), $m).' '.$y;}}if($is_time) {list($h, $m, $s)  = explode(':', $time);$result .= ' в '.$h.':'.$m;}return $result;}
function invate_check($a='') { global $invate,$db,$prefix; if ($invate['status']!=1) return true; if ($a=='') return false; else { invate_expire(); list($count)=$db->sql_fetchrow($db->sql_query("SELECT COUNT(*) FROM ".$prefix."_invates WHERE `invate`='".$a."' AND `nuid`='0'")); if ($count==1) return true; else return false; } }
function invate_update ($a=array()) { global $db,$prefix,$invate; if ($invate['status']!=1) return true; $db->sql_query("UPDATE ".$prefix."_invates SET nuid='".$a['uname']."' WHERE `invate`='".$a['invate']."'"); }
?>